### ISSUE TITLE
StdIn/Stdout instead of files?

### ISSUE THREAD

**Issue by leonardorame** [ucs198604/dicom2jpg#2]
Hi, instead of opening files, can this library read data from stdin and output to stdout?. This could be useful when you need to pipe image data to other programs.

Regards,
Leonardo.

**Comment by ykuo2** [comment]
Hi, that's beyond my ability now. I don't even have any clue what's stdin/stdout... 
It sounds really cool to process the data and pass results to another program. I wish I knew how to do it.

**Comment by ykuo2** [comment]
@leonardorame Hi, I've added ByteIO → ndarray function, is that what you need?
