### ISSUE TITLE
AttributeError: 'FileDataset' object has no attribute 'SOPClassUID'

### ISSUE THREAD

**Issue by bateaurouge** [ucs198604/dicom2jpg#4]
Hello,

Thanks for this package.

I'm getting this error:
AttributeError: 'FileDataset' object has no attribute 'SOPClassUID'

I checked and my dicoms do not have this attribute

Thanks

**Comment by ykuo2** [comment]
Sorry for my late replying...being extremely busy recently.
I wrongly assumed the tag is universal.
Please update to the new version
`pip install -U dicom2jpg`

Hope it will fix this problem
